### PR TITLE
Notes for CMake on Ubuntu 16.04 and 17.04

### PR DESCRIPTION
**Pull request by malynda**
I had problems building on 17.04 with the default CMake (3.7.2) so upgraded to 3.9.0.rc5. Added notes about how to update to version 3.9.
Building on 16.04 with default CMake version of 3.5.1 went just swimmingly. Noted this as well.

### CODE REVIEW

**Comment by lovettchris** [comment]
Weird that 3.7 doesn't work yet on Ubuntu 16 3.5 works fine?  What was the error?

**Comment by wuchangjin** [comment]
ibraries/utilities/include/../tcc/Archiver.tcc:185:9: error: no matching function for call to ‘ell::utilities::Unarchiver::UnarchiveArray(const char*&, std::vector<long long unsigned int, std::allocator<long long unsigned int> >&)’
         UnarchiveArray(name, arr);
why there is an error ? （on ubuntu16.04，cmake3.10.0-rc4,llvm3.9.1）,what shall i do ?thanks

**Comment by lovettchris** [comment]
So I think you are running into a gcc version issue, not a cmake version issue.  Can you try the latest bits and see if it works on gcc 5.4 ?  If not you may need to move to gcc 6.4.  I think we should leave the ubuntu setup saying minimum cmake version required is 3.5

**Comment by lovettchris** [comment]
Thanks for the pull request, but we'd prefer to leave our setup instructions just pointing the user to https://cmake.org/ so they can follow the instructions there (which keep changing).  For example, latest cmake is now 3.13.  This way is less doc maintenance for us.
